### PR TITLE
Enhanced ESP32 series support

### PR DESCRIPTION
**Pull request by suapapa**
- Fixed build failures with the recent esp-hal 0.22.0.
- Added support for the ESP32-S2.
- Minor fix on `ci-esp.sh`.

### CODE REVIEW

**Review by AdinAck — APPROVED** [review]
Thank you! I made some minor changes, but this looks great!

**Comment by AdinAck** [comment]
I don't know why the esp CI fails, I'm not sure it ever worked, passes CI on my computer.

**Comment by suapapa** [comment]
> I don't know why the esp CI fails, I'm not sure it ever worked, passes CI on my computer.

I think `ci-esp.sh` should run with `--install-esp` for install esp toolchain in the gitlab CI.
Anyway, thanks for merge this. 🚀

**Comment by AdinAck** [comment]
Ah wow, I forgot how my own script worked. You are right, but it also fails for some other unknown reasons. Thanks again!

**Pull request merged**
